Update main.rs
Using `gen_range(1,101)` instead of `gen_range(1..101)` arises the following error - 

> `error[E0277]: the trait bound `{integer}: SampleRange<_>` is not satisfied`